title: Minsoo Kim's Journal Archive
email: minsookim9@gmail.com
# description: >-
#   Minsoo Kim's journal archive
baseurl: "/blog"
url: "https://vv137.github.io"

minima:
  date_format: "%Y-%m-%d"
  social_links:
    github: vv137

header_pages:
  - about.md
  - links.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
