title: Minsoo Kim's Blog
email: minsookim9@gmail.com
description: >-
  Minsoo Kim's journal archive
baseurl: "/blog"
url: "https://vv137.github.io"
github_username: vv137

minima:
  date_format: "%Y-%m-%d"
  social_links: #

header_pages:
  - about.md

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag
