title: Minsoo Kim's Blog
email: minsookim9@gmail.com
description: >-
  Minsoo Kim's journal archive
baseurl: "/blog"
url: "https://vv137.github.io"
github_username: vv137

# Build settings
theme: minima
plugins:
  - jekyll-feed
